export enum ActionType {
    openModal = "OPEN_MODAL",
    closeModal = "CLOSE_MODAL",
    fetchBooks = "FETCH_BOOKS",
    fetchBooksSuccess = "FETCH_BOOKS_SUCCESS",
    fetchBooksFailure = "FETCH_BOOKS_FAILURE",
    deleteBook = "DELETE_BOOK",
    deleteBookSuccess = "DELETE_BOOK_SUCCESS",
    deleteBookFailure = "DELETE_BOOK_FAILURE",
    addBook = "ADD_BOOK",
    addBookSuccess = "ADD_BOOK_SUCCESS",
    addBookFailure = "ADD_BOOK_FAILURE",
    createUser = "REGISTER_USER",
    createUserSuccess = "CREATE_USER_SUCCESS",
    createUserFailure = "CREATE_USER_FAILURE",
    logInUser = "LOG_IN_USER",
    logInUserSuccess = "LOG_IN_USER_SUCCESS",
    logInUserFailure = "LOG_IN_USER_FAILURE",
    logOutUser = "LOG_OUT_USER",
    logOutUserFailure = "LOG_OUT_USER_FAILURE",
    logOutUserSuccess = "LOG_OUT_USER_SUCCESS",
    authUser = "AUTHENTICATE_USER",
    authUserSuccess = "AUTHENTICATE_USER_SUCCESS",
    authUserFailure = "AUTHENTICATE_USER_FAILURE",
}